##
## NDK Rest configuration file. Lines beginning with # are comments.
##

# Console log level: TRACE, DEBUG, INFO, WARN, ERROR (default: INFO)
# log_level = "INFO"

[network]
# Bind to this network address (default: "127.0.0.1:7773")
# listen_addr = "127.0.0.1:7773"

# Enable permissive CORS (default: false)
# Permissive mode should NOT be used in production!
# permissive_cors = false

[limit]
# Max filters that can be sent to /events endpoint (default: 10)
# max_filters = 10

# Max events allowed per filters (default: 100)
# max_events_per_filter = 100

[nostr]
# Read/Write relays
relays = ["wss://relay.damus.io"]

# Discovery relays (used for gossip)
discovery = ["wss://relay.damus.io"]

# Use the gossip model (default: false)
gossip = true

[redis]
# Enable redis (default: false)
enabled = false

# Redis endpoint (default: "redis://127.0.0.1")
# endpoint = "redis://127.0.0.1"

# Expiration in secs (default: 60)
expiration = 60
